# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "TailwindCSS starter blank"
license = "MIT"
licenselink = "https://github.com/javifm86/hugo-tailwindcss-starter/blob/master/LICENSE"
description = "Starter blank theme for Hugo with TailwindCSS"
homepage = ""
tags = []
features = []
min_version = "0.41"

[author]
  name = "Javier Fernández"
  homepage = "https://javifm.com"